"""Tests lib.trigfile.TrigFile's binary reader using fixture binaries under fixtures/trig_ascii/*.trg.
quad*/fan.trig2l.trg were generated by running the original Perl maketrig.pl on small synthetic
ASCII sources, so they're ground truth for the wire format independent of this Python port.

deftrig1.trig2l.trg/deftrig1.trig2b.trg/deftrig2.trig2l.trg are built from the real ASCII trig
definitions used by the snap regression suite's deformation model
(cmn_test_deftrig1.trg/cmn_test_deftrig2.trg), but by this Python port itself rather than Perl:
those two real sources each contain a point-ordering tie (an actual x-coordinate duplicate in one,
a fully-surrounded interior point's arbitrary neighbour-cycle start in the other, see
test_golden_fixtures.py) that Perl's own maketrig.pl only ever resolved via its hash iteration
order - not independently reproducible, so no single Perl run of it was a reliable byte-for-byte
target. Before switching to this Python-built version, its point set and triangulation topology
(both order-independent) were confirmed identical to a real maketrig.pl run's output.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from lib.trigfile import TrigFile, build_trig_file

FIXTURES = Path(__file__).parent / "fixtures" / "trig_ascii"


class TestReadsGroundTruthBinaries:
    """Python's reader decodes the ground-truth TRIG2L/TRIG2B binaries to the expected values."""

    def test_little_endian_header_and_extents(self) -> None:
        """A TRIG2L binary's header fields and point/dimension counts decode as expected."""
        trig = TrigFile(FIXTURES / "deftrig1.trig2l.trg")
        assert trig.titles == ("Patch 1", "Deformation model", "Test model 1")
        assert trig.crdsys_code == "NZGD1949"
        assert (trig.npts, trig.dimension) == (100, 2)
        assert trig.ymin == pytest.approx(-40.078884)
        assert trig.ymax == pytest.approx(-39.921779)
        assert trig.xmin == pytest.approx(176.110594)
        assert trig.xmax == pytest.approx(176.277709)

    def test_big_endian_matches_little_endian_source(self) -> None:
        """The same source built as TRIG2B decodes to identical values as its TRIG2L counterpart."""
        little = TrigFile(FIXTURES / "deftrig1.trig2l.trg")
        big = TrigFile(FIXTURES / "deftrig1.trig2b.trg")
        assert big.titles == little.titles
        assert big.crdsys_code == little.crdsys_code
        assert (big.npts, big.dimension) == (little.npts, little.dimension)
        assert big._point_coords == little._point_coords  # pylint: disable=protected-access
        assert big._point_data == little._point_data  # pylint: disable=protected-access
        assert big._topology_index == little._topology_index  # pylint: disable=protected-access
        assert big._topology_data == little._topology_data  # pylint: disable=protected-access

    def test_second_source_has_distinct_header_and_topology(self) -> None:
        """A different source file decodes its own distinct header and topology sizes."""
        trig = TrigFile(FIXTURES / "deftrig2.trig2l.trg")
        assert trig.titles == ("Patch2", "Deformation model", "Test2")
        assert trig.crdsys_code == "NZGD1949"
        assert (trig.npts, trig.dimension) == (100, 2)
        assert len(trig._topology_data) == 1248  # pylint: disable=protected-access

    def test_rejects_invalid_signature(self, tmp_path: Path) -> None:
        """A file that doesn't start with a recognized trig signature raises `ValueError`."""
        bad_file = tmp_path / "not_a_trig_file.trg"
        bad_file.write_bytes(b"not a valid trig signature at all")
        with pytest.raises(ValueError, match="signature incorrect"):
            TrigFile(bad_file)


def _rotate_to(values: tuple[int, ...], offset: int) -> tuple[int, ...]:
    """Rotates `values` to start `offset` positions later, wrapping around the end."""
    return values[offset:] + values[:offset]


class TestBuildsGroundTruthBinaries:
    """Python's builder reproduces maketrig.pl's output byte-for-byte from small synthetic ASCII
    sources - not the two large real regression fixtures above, each of which had its own
    point-ordering tie (see the module docstring). maketrig.pl broke such ties using Perl's
    per-process-randomized hash iteration order, so no single run of it against real-world data
    was a reliable byte-for-byte target; these synthetic sources were built without ties
    specifically so a single ground-truth run is trustworthy."""

    def test_little_endian_matches_ground_truth(self, tmp_path: Path) -> None:
        """A quadrilateral (2 triangles, all boundary points) builds byte-identical TRIG2L output."""
        output = tmp_path / "quad.trig2l.trg"
        build_trig_file(FIXTURES / "quad.txt", output, big_endian=False)
        assert output.read_bytes() == (FIXTURES / "quad.trig2l.trg").read_bytes()

    def test_big_endian_matches_ground_truth(self, tmp_path: Path) -> None:
        """The same source built as TRIG2B is byte-identical to the ground-truth TRIG2B binary."""
        output = tmp_path / "quad.trig2b.trg"
        build_trig_file(FIXTURES / "quad.txt", output, big_endian=True)
        assert output.read_bytes() == (FIXTURES / "quad.trig2b.trg").read_bytes()

    def test_format_none_uses_source_header(self, tmp_path: Path) -> None:
        """`big_endian=None` uses the source's own `FORMAT: TRIG2L` header rather than defaulting."""
        output = tmp_path / "quad_default.trg"
        build_trig_file(FIXTURES / "quad.txt", output, big_endian=None)
        assert output.read_bytes() == (FIXTURES / "quad.trig2l.trg").read_bytes()

    def test_triangle_winding_is_normalized(self, tmp_path: Path) -> None:
        """A source with one `T` record listed in the opposite (clockwise) order still builds the
        same output - triangle winding is normalized regardless of how the source wrote it."""
        output = tmp_path / "quad_reversed.trig2l.trg"
        build_trig_file(FIXTURES / "quad_reversed.txt", output, big_endian=False)
        assert output.read_bytes() == (FIXTURES / "quad.trig2l.trg").read_bytes()

    def test_closed_fan_around_interior_point(self, tmp_path: Path) -> None:
        """A hub point fully surrounded by 5 triangles has a closed neighbour cycle rather than a
        boundary path. Its starting neighbour in that cycle is arbitrary - even maketrig.pl's own
        choice of it depended on Perl's unordered hash iteration for a fully-surrounded point - so
        a rotation of the expected cycle is accepted here, rather than requiring an exact match to
        one ground-truth run's arbitrary starting choice. Every other (boundary) point's topology
        has a unique, non-arbitrary starting neighbour and is still checked for an exact match."""
        output = tmp_path / "fan.trig2l.trg"
        build_trig_file(FIXTURES / "fan.txt", output, big_endian=False)
        built = TrigFile(output)
        truth = TrigFile(FIXTURES / "fan.trig2l.trg")

        assert built._point_coords == truth._point_coords  # pylint: disable=protected-access
        assert built._point_data == truth._point_data  # pylint: disable=protected-access
        assert built._topology_index == truth._topology_index  # pylint: disable=protected-access

        # Each point's on-disk entry in `_topology_data` runs from its own offset (in
        # `_topology_index`) to the next point's offset (or the array's end, for the last point).
        entry_bounds = (*truth._topology_index, len(truth._topology_data))  # pylint: disable=protected-access
        for entry_start, entry_end in zip(entry_bounds, entry_bounds[1:]):
            built_entry = built._topology_data[entry_start:entry_end]  # pylint: disable=protected-access
            truth_entry = truth._topology_data[entry_start:entry_end]  # pylint: disable=protected-access
            neighbour_count = truth_entry[0]
            assert built_entry[0] == neighbour_count
            truth_nodes = truth_entry[1 : 1 + neighbour_count]

            if 0 in truth_nodes:
                # Boundary point: a path with a unique, non-arbitrary starting neighbour.
                assert built_entry == truth_entry
                continue

            # Interior point: a closed cycle with an arbitrary starting neighbour - rotate built's
            # arrays to start at the same neighbour as truth's before comparing.
            built_nodes = built_entry[1 : 1 + neighbour_count]
            offset = built_nodes.index(truth_nodes[0])
            assert _rotate_to(built_nodes, offset) == truth_nodes
            assert _rotate_to(built_entry[1 + neighbour_count :], offset) == truth_entry[1 + neighbour_count :]


class TestBuildValidatesSource:
    """`build_trig_file` raises `ValueError` on the first problem found in a malformed source."""

    def test_missing_required_header(self, tmp_path: Path) -> None:
        """A source missing a required header record raises `ValueError` naming it."""
        source = tmp_path / "missing_header.txt"
        source.write_text(
            "FORMAT TRIG2L\nHEADER0 x\nHEADER1 x\nHEADER2 x\nNDIM 1\nP 1 0 0 1.0\nP 2 1 1 2.0\nP 3 1 0 3.0\nT 1 2 3\n"
        )
        with pytest.raises(ValueError, match="CRDSYS"):
            build_trig_file(source, tmp_path / "out.trg", big_endian=False)

    def test_inconsistent_data_dimension(self, tmp_path: Path) -> None:
        """A point with a different number of data values than the first point raises `ValueError`."""
        source = tmp_path / "bad_dimension.txt"
        source.write_text(
            "FORMAT TRIG2L\nHEADER0 x\nHEADER1 x\nHEADER2 x\nCRDSYS NZGD2000\nNDIM 1\n"
            "P 1 0 0 1.0\nP 2 1 1 2.0 3.0\nP 3 1 0 3.0\nT 1 2 3\n"
        )
        with pytest.raises(ValueError, match="inconsistent"):
            build_trig_file(source, tmp_path / "out.trg", big_endian=False)

    def test_triangle_references_undefined_point(self, tmp_path: Path) -> None:
        """A `T` record naming a point id that was never defined raises `ValueError`."""
        source = tmp_path / "bad_triangle.txt"
        source.write_text(
            "FORMAT TRIG2L\nHEADER0 x\nHEADER1 x\nHEADER2 x\nCRDSYS NZGD2000\nNDIM 1\n"
            "P 1 0 0 1.0\nP 2 1 1 2.0\nP 3 1 0 3.0\nT 1 2 9\n"
        )
        with pytest.raises(ValueError, match="not defined"):
            build_trig_file(source, tmp_path / "out.trg", big_endian=False)
