"""Tests lib.gridfile.GridFile's binary and ASCII row formats using fixture binaries under
fixtures/grid_ascii/*.grd. Those binaries were generated by running the original Perl
GridFile.pm (via its makegrid.pl/dumpgrid.pl CLIs) on the adjacent *.txt ASCII sources, so
they're ground truth for the wire format independent of this Python port. Tests assert Python's
writer produces byte-identical output to that ground truth for the same source, and that
Python's reader decodes it to the expected values.
"""

from __future__ import annotations

import io
from pathlib import Path

import pytest

from lib.gridfile import GridFile, GridFormat, WriteOptions

FIXTURES = Path(__file__).parent / "fixtures" / "grid_ascii"


def _read_all_rows(grid: GridFile) -> list[list[float | None]]:
    """Reads every row via the private row accessor - no public row-reading API exists yet."""
    return [grid._get_row(row) for row in range(grid.ngridy)]  # pylint: disable=protected-access


class TestReadsGroundTruthBinaries:
    """Python's reader decodes the ground-truth GRID2L binaries to the expected values."""

    def test_simple_all_defined_single_dimension(self) -> None:
        """A fully-defined single-dimension grid decodes to its known source values."""
        grid = GridFile(FIXTURES / "simple.grid2l.grd")
        assert (grid.ngridx, grid.ngridy, grid.dimension) == (6, 3, 1)
        assert _read_all_rows(grid) == [
            [10.0, 12.0, 15.0, 11.0, 9.0, 8.0],
            [-5.0, 0.0, 3.0, 7.0, 100.0, -100.0],
            [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
        ]

    def test_gaps_preserve_undefined_positions_and_subset(self) -> None:
        """Leading, trailing, and internal gaps decode to None; an all-undefined row too."""
        grid = GridFile(FIXTURES / "gaps.grid2l.grd")
        assert _read_all_rows(grid) == [
            [None, None, 20.0, None, 25.0, 30.0, None, None],
            [None] * 8,
        ]

    def test_wide_handles_large_magnitude_values(self) -> None:
        """Values large enough to force wider byte widths still decode correctly."""
        grid = GridFile(FIXTURES / "wide.grid2l.grd")
        assert _read_all_rows(grid) == [
            [0.0, 40000.0, -40000.0, 40000.0, -40000.0],
            [0.0, 2000000000.0, -2000000000.0, 2000000000.0, -2000000000.0],
        ]

    def test_multidim_interleaves_values_per_column(self) -> None:
        """A multi-dimension grid's row values interleave as (col0dim0, col0dim1, col1dim0, ...)."""
        grid = GridFile(FIXTURES / "multidim.grid2l.grd")
        assert grid.dimension == 2
        assert _read_all_rows(grid) == [
            [1.0, 100.0, 2.0, 200.0, None, None, 4.0, 400.0, 5.0, 500.0],
            [-1.0, -10.0, -2.0, -20.0, -3.0, -30.0, -4.0, -40.0, -5.0, -50.0],
        ]

    def test_integer_vres_raw_row_values_are_prescaled_ints(self) -> None:
        """The binary stores raw pre-scaled integers; real-world values need `* grid.vres`."""
        grid = GridFile(FIXTURES / "integer_vres.grid2l.grd")
        assert grid.vres == pytest.approx(0.01)
        assert _read_all_rows(grid) == [
            [100.0, 200.0, 300.0, 400.0],
            [-100.0, -200.0, -300.0, -400.0],
        ]


class TestWriteMatchesGroundTruthByteForByte:  # pylint: disable=too-few-public-methods
    """Python reads each ASCII source and writes GRID2L; output must be byte-identical to the
    ground-truth binary generated from the same source - the strongest possible check that the
    write path (ASCII-source reading, resolution scaling, and row encoding) matches, not just
    that decoded values happen to look right."""

    @pytest.mark.parametrize("name", ["simple", "gaps", "wide", "multidim", "integer_vres"])
    def test_write_byte_identical_to_ground_truth(self, name: str, tmp_path: Path) -> None:
        """Writing each ASCII source to GRID2L reproduces the ground-truth binary exactly."""
        grid = GridFile(FIXTURES / f"{name}.txt")
        out_path = tmp_path / f"{name}.grd"
        grid.write_to_file(out_path)
        assert out_path.read_bytes() == (FIXTURES / f"{name}.grid2l.grd").read_bytes()


class TestFixedAndBigEndianAndGeoidFormats:
    """Covers the formats/paths the GRID2L-focused tests above don't: the FIXED row encoding
    (GEOID/GRID1x), big-endian byte order dispatched through GridFile itself (not just the
    isolated EndianCodec tests), and GEOID's special-casing (dimension/latlon hardcoded to 1,
    NDIM/LATLON headers omitted)."""

    def test_read_fixed_little_endian(self) -> None:
        """GRID1L (FIXED, little-endian) decodes to the same values as its GRID2L counterpart."""
        grid = GridFile(FIXTURES / "simple.grid1l.grd")
        assert _read_all_rows(grid) == [
            [10.0, 12.0, 15.0, 11.0, 9.0, 8.0],
            [-5.0, 0.0, 3.0, 7.0, 100.0, -100.0],
            [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
        ]

    def test_read_fixed_preserves_undefined_positions(self) -> None:
        """GRID1L's reserved sentinel correctly decodes back to None at gap positions."""
        grid = GridFile(FIXTURES / "gaps.grid1l.grd")
        assert _read_all_rows(grid) == [
            [None, None, 20.0, None, 25.0, 30.0, None, None],
            [None] * 8,
        ]

    def test_read_fixed_big_endian(self) -> None:
        """GRID1B (FIXED, big-endian) decodes correctly via GridFile's own byte-order dispatch."""
        grid = GridFile(FIXTURES / "simple.grid1b.grd")
        assert _read_all_rows(grid)[0] == [10.0, 12.0, 15.0, 11.0, 9.0, 8.0]

    def test_read_compressed_big_endian(self) -> None:
        """GRID2B (COMPRESSED, big-endian) decodes correctly via GridFile's own byte-order dispatch."""
        grid = GridFile(FIXTURES / "simple.grid2b.grd")
        assert _read_all_rows(grid)[0] == [10.0, 12.0, 15.0, 11.0, 9.0, 8.0]

    def test_read_geoid_forces_single_dimension_and_latlon(self) -> None:
        """GEOID hardcodes dimension=1/latlon=True rather than reading them from the file."""
        grid = GridFile(FIXTURES / "simple.geoid.grd")
        assert (grid.dimension, grid.latlon) == (1, True)
        assert _read_all_rows(grid)[0] == [10.0, 12.0, 15.0, 11.0, 9.0, 8.0]

    @pytest.mark.parametrize(
        ("source", "output_format", "ground_truth"),
        [
            ("simple", GridFormat.GRID1L, "simple.grid1l.grd"),
            ("gaps", GridFormat.GRID1L, "gaps.grid1l.grd"),
            ("simple", GridFormat.GRID1B, "simple.grid1b.grd"),
            ("simple", GridFormat.GRID2B, "simple.grid2b.grd"),
            ("simple", GridFormat.GEOID, "simple.geoid.grd"),
        ],
    )
    def test_write_byte_identical_to_ground_truth(
        self, source: str, output_format: GridFormat, ground_truth: str, tmp_path: Path
    ) -> None:
        """Writing each ASCII source to a non-default output format matches Perl's own output."""
        grid = GridFile(FIXTURES / f"{source}.txt")
        out_path = tmp_path / "out.grd"
        grid.write_to_file(out_path, WriteOptions(output_format=output_format))
        assert out_path.read_bytes() == (FIXTURES / ground_truth).read_bytes()


class TestAsciiOutput:  # pylint: disable=too-few-public-methods
    """Covers writing *to* ASCII - the tests above only ever use ASCII as a read-side source."""

    def test_write_ascii_matches_perl_dump(self, tmp_path: Path) -> None:
        """Writing a binary source to ASCII matches real Perl's own dumpgrid.pl output."""
        grid = GridFile(FIXTURES / "simple.grid2l.grd")
        out_path = tmp_path / "simple.dump.txt"
        grid.write_to_file(out_path, WriteOptions(output_format=GridFormat.ASCII, real=True))
        assert out_path.read_bytes() == (FIXTURES / "simple.dump.txt").read_bytes()


class TestWriteToStream:  # pylint: disable=too-few-public-methods
    """write_to_file and write_to_stream produce identical output - the former just wraps the
    latter around an opened path, so a caller with an already-open stream (e.g. stdout) can use
    write_to_stream directly instead."""

    def test_write_to_stream_matches_write_to_file(self, tmp_path: Path) -> None:
        """Writing to an in-memory stream matches writing the same grid to a file."""
        grid = GridFile(FIXTURES / "simple.grid2l.grd")
        options = WriteOptions(output_format=GridFormat.ASCII, real=True)

        out_path = tmp_path / "via_file.txt"
        grid.write_to_file(out_path, options)

        buffer = io.BytesIO()
        grid.write_to_stream(buffer, options)

        assert buffer.getvalue() == out_path.read_bytes()
