
#ifndef SNAPPLOT_EVENTIDS_HPP
#define SNAPPLOT_EVENTIDS_HPP

enum
{
    // Menu event

    CMD_FILE_FIRST = 1,
    CMD_FILE_SAVECONFIG,
    CMD_FILE_RESTORECONFIG,
    CMD_FILE_EXPORTDXF,
    CMD_FILE_EXPORTIMAGE,
    CMD_FILE_PRINTMAP,
    CMD_FILE_PRINTPREVIEW,
    CMD_FILE_CLOSE,
    CMD_FILE_LAST = CMD_FILE_CLOSE,

    CMD_COPY_FIRST,
    CMD_COPY_MAP = CMD_COPY_FIRST,
    CMD_COPY_DETAILS,
    CMD_COPY_STATIONS,
    CMD_COPY_OBSLIST,
    CMD_COPY_LAST = CMD_COPY_OBSLIST,

    CMD_VIEW_FIRST,
    CMD_VIEW_ALL = CMD_VIEW_FIRST,
    CMD_VIEW_ZOOMOUT,
    CMD_VIEW_ZOOMPREV,
    CMD_VIEW_STATIONLIST,
    CMD_VIEW_OBSLIST,
    CMD_VIEW_DETAILS,
    CMD_VIEW_ADD_COLOUR,
    CMD_VIEW_MAPFONT,
    CMD_VIEW_LAST = CMD_VIEW_MAPFONT,

    CMD_STATION_FIRST,
    CMD_STATION_COLOURBY  = CMD_STATION_FIRST,
    CMD_STATION_OPTIONS,
    CMD_STATION_HIGHLIGHT,
    CMD_STATION_HIDESHOW,
    CMD_STATION_IGNOREOFFSETS,
    CMD_STATION_FINDSTATION,
    CMD_STATION_LAST = CMD_STATION_FINDSTATION,

    CMD_STATION_COLOURBY_USAGE,

    CMD_DATA_FIRST,
    CMD_DATA_COLOURBY = CMD_DATA_FIRST,
    CMD_DATA_OPTIONS,
    CMD_DATA_HIGHLIGHT,
    CMD_DATA_LISTOPTIONS,
    CMD_DATA_LAST = CMD_DATA_LISTOPTIONS,

    CMD_COLOURBY_FIRST,
    CMD_COLOURBY_DATATYPE = CMD_COLOURBY_FIRST,
    CMD_COLOURBY_DATAFILE,
    CMD_COLOURBY_RESIDUAL,
    CMD_COLOURBY_REDUNDANCY,
    CMD_COLOURBY_LAST = CMD_COLOURBY_REDUNDANCY,

    CMD_ERROR_FIRST,
    CMD_ERROR_OPTIONS = CMD_ERROR_FIRST,
    CMD_ERROR_LAST = CMD_ERROR_OPTIONS,

    CMD_HELP_FIRST,
    CMD_HELP_HELP = CMD_HELP_FIRST,
    CMD_HELP_ABOUT,
    CMD_HELP_LAST = CMD_HELP_ABOUT,

    CMD_USER_CONFIG_FIRST

};

#endif