#!/usr/bin/perl
use LINZ::Geodetic::Util::GridFile;
if( ! @ARGV )
{
    require Pod::Usage;
    require Pod::Find;
    Pod::Usage::pod2usage( 
        -verbose => 2,
        -input => Pod::Find::pod_where( {-inc=>1}, 'LINZ::Geodetic::Util::GridFile' )
        );
    exit();
}
LINZ::Geodetic::Util::GridFile::Convert
