name: Run regression tests on push to master
on:
  push:
    branches:
      - "*"
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  package:
    runs-on: ${{ matrix.distro }}
    strategy:
      fail-fast: false
      matrix:
        distro: [ "ubuntu-22.04", "ubuntu-24.04" ]
    env:
      PACKAGECLOUD_REPOSITORY: test
    steps:
      - name: Checkout source
        uses: actions/checkout@v3.6.0
      - name: Install dependencies
        run: |
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install cmake g++ libboost-dev libboost-math-dev libboost-regex-dev python3
      - name: Build snap command line utilities and run regression tests
        run: python3 build.py release test --no-gui
